--- #YAML:1.0
name:               WWW-Foursquare-RSS
version:            0.01
abstract:           Perl interface to the Foursquare.com RSS feeds
author:
    - Michael Aquilina <aquilina@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:         0
    Date::Parse:  0
    DateTime:     0
    LWP::Simple:  0
    XML::Simple:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
